# Generated by Django 6.0.1 on 2026-01-20 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('base_unit', models.CharField(default='EA', max_length=32)),
                ('purchase_unit', models.CharField(default='EA', max_length=32)),
                ('purchase_conversion_factor', models.DecimalField(decimal_places=3, default=1, help_text='1 purchase_unit = N base_unit', max_digits=12)),
                ('sales_unit', models.CharField(default='EA', max_length=32)),
                ('sales_conversion_factor', models.DecimalField(decimal_places=3, default=1, help_text='1 sales_unit = N base_unit', max_digits=12)),
                ('spec', models.CharField(blank=True, max_length=255)),
                ('is_resell', models.BooleanField(default=False)),
                ('is_stock_managed', models.BooleanField(default=False)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0.1, help_text='부가세율 (예: 0.1 = 10%, 0 = 면세)', max_digits=4)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('code__isnull', False)), fields=('code',), name='unique_product_code_not_null')],
            },
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_components', to='product.product')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_parents', to='product.product')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('parent', models.F('component')), _negated=True), name='bom_no_self_reference'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='bom_quantity_positive')],
                'unique_together': {('parent', 'component')},
            },
        ),
    ]
