# Generated by Django 4.2 on 2025-11-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_usercompanyrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompanyrole',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('staff', 'Staff'), ('accountant', 'Accountant')], max_length=20),
        ),
    ]
