# Generated by Django 4.2 on 2026-01-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usercompanyrole_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='brand_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', '승인 대기'), ('active', '승인 완료'), ('rejected', '승인 거절')], default='pending', max_length=10),
        ),
    ]
