# Generated by Django 4.2 on 2026-01-10 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_address_company_base_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='company',
        ),
        migrations.AlterUniqueTogether(
            name='usercompanyrole',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usercompanyrole',
            name='company',
        ),
        migrations.RemoveField(
            model_name='usercompanyrole',
            name='user',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='UserCompanyRole',
        ),
    ]
