# Generated by Django 6.0.1 on 2026-03-30 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='매장코드')),
                ('name', models.CharField(max_length=100, verbose_name='매장명')),
            ],
            options={
                'verbose_name': '매장',
                'verbose_name_plural': '매장',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(db_index=True, default='matepos', max_length=20, verbose_name='데이터 출처')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='원본 데이터')),
                ('business_date', models.DateField(db_index=True, verbose_name='영업일')),
                ('sold_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='주문일시')),
                ('order_seq', models.PositiveSmallIntegerField(verbose_name='주문번호(일련)')),
                ('channel_order_no', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='채널 주문번호')),
                ('order_category', models.CharField(max_length=10, verbose_name='주문구분')),
                ('channel', models.CharField(choices=[('HALL', '홀'), ('BAEMIN', '배민'), ('COUPANG', '쿠팡'), ('YOGIYO', '요기요'), ('DDANGYO', '땡겨요'), ('KARROT', '당근')], db_index=True, default='HALL', max_length=20, verbose_name='채널')),
                ('channel_detail', models.CharField(max_length=20, verbose_name='주문채널상세')),
                ('order_type', models.CharField(max_length=10, verbose_name='주문타입')),
                ('payment_status', models.CharField(choices=[('결제완료', '결제완료'), ('결제취소', '결제취소')], db_index=True, default='결제완료', max_length=10, verbose_name='결제상태')),
                ('payment_method', models.CharField(max_length=20, verbose_name='결제수단')),
                ('delivery_company', models.CharField(blank=True, max_length=20, null=True, verbose_name='배달업체')),
                ('sale_amount', models.IntegerField(default=0, verbose_name='판매금액')),
                ('discount_amount', models.IntegerField(default=0, verbose_name='할인금액')),
                ('net_sale_amount', models.IntegerField(default=0, verbose_name='매출(취소)금액')),
                ('channel_delivery_fee', models.IntegerField(default=0, verbose_name='채널배달료(매출제외)')),
                ('channel_discount', models.IntegerField(default=0, verbose_name='채널할인(매출제외)')),
                ('actual_sale_amount', models.IntegerField(default=0, verbose_name='실매출액')),
                ('taxable_amount', models.IntegerField(default=0, verbose_name='과세금액')),
                ('vat', models.IntegerField(default=0, verbose_name='부가세')),
                ('non_taxable_amount', models.IntegerField(default=0, verbose_name='비과세금액')),
                ('cup_deposit', models.IntegerField(default=0, verbose_name='일회용컵보증금')),
                ('online_delivery_fee', models.IntegerField(default=0, verbose_name='온라인채널 배달료')),
                ('org_business_date', models.DateField(blank=True, null=True, verbose_name='원래 영업일')),
                ('org_order_seq', models.CharField(blank=True, max_length=20, null=True, verbose_name='원래 주문번호')),
                ('mate_qr_order_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='MATE QR 주문번호')),
                ('note', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sale.store', verbose_name='매장')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문',
                'ordering': ['-business_date', '-order_seq'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item_seq', models.PositiveSmallIntegerField(verbose_name='항목순번')),
                ('goods_cd', models.CharField(max_length=50, verbose_name='상품코드')),
                ('goods_nm', models.CharField(max_length=200, verbose_name='상품명')),
                ('app_prc', models.IntegerField(default=0, verbose_name='적용단가')),
                ('sale_qty', models.IntegerField(default=0, verbose_name='수량')),
                ('sale_amt', models.IntegerField(default=0, verbose_name='판매금액')),
                ('item_dc_amt', models.IntegerField(default=0, verbose_name='항목할인')),
                ('taxable_amount', models.IntegerField(default=0, verbose_name='과세금액')),
                ('vat', models.IntegerField(default=0, verbose_name='부가세')),
                ('non_taxable_amount', models.IntegerField(default=0, verbose_name='비과세금액')),
                ('sale_except_amt', models.IntegerField(default=0, verbose_name='매출제외금액')),
                ('sale_except_yn', models.CharField(default='N', max_length=1, verbose_name='매출제외여부')),
                ('packing_yn', models.CharField(default='N', max_length=1, verbose_name='포장여부')),
                ('item_details', models.JSONField(blank=True, default=list, verbose_name='세트구성')),
                ('item_opt_details', models.JSONField(blank=True, default=list, verbose_name='옵션구성')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sale.sale', verbose_name='주문')),
            ],
            options={
                'verbose_name': '주문 상품',
                'verbose_name_plural': '주문 상품',
                'ordering': ['sale', 'item_seq'],
                'unique_together': {('sale', 'item_seq')},
            },
        ),
        migrations.CreateModel(
            name='SaleTender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tender_seq', models.PositiveSmallIntegerField(verbose_name='결제순번')),
                ('tender_cd', models.CharField(max_length=30, verbose_name='결제수단코드')),
                ('tender_nm', models.CharField(max_length=50, verbose_name='결제수단명')),
                ('tender_amt', models.IntegerField(default=0, verbose_name='결제금액')),
                ('change_amt', models.IntegerField(default=0, verbose_name='거스름돈')),
                ('pre_tender_yn', models.CharField(default='N', max_length=1, verbose_name='선결제여부')),
                ('return_yn', models.CharField(default='N', max_length=1, verbose_name='반환여부')),
                ('approval_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='승인번호')),
                ('approval_dt', models.CharField(blank=True, max_length=20, null=True, verbose_name='승인일시')),
                ('pur_nm', models.CharField(blank=True, max_length=50, null=True, verbose_name='카드사명')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='sale.sale', verbose_name='주문')),
            ],
            options={
                'verbose_name': '결제 수단',
                'verbose_name_plural': '결제 수단',
                'ordering': ['sale', 'tender_seq'],
                'unique_together': {('sale', 'tender_seq')},
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['business_date', 'channel'], name='sale_sale_busines_aa69f3_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['business_date', 'payment_status'], name='sale_sale_busines_632407_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sale',
            unique_together={('store', 'business_date', 'order_seq')},
        ),
    ]
