# Generated by Django 6.0.1 on 2026-04-05 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBaeminInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ad_campaign_key', models.CharField(blank=True, max_length=30, verbose_name='광고유형')),
                ('is_club_member', models.BooleanField(default=False, verbose_name='배민클럽 여부')),
                ('delivery_carry_type', models.CharField(blank=True, max_length=20, verbose_name='배달방식')),
                ('shop_discount', models.IntegerField(default=0, verbose_name='사장님부담 할인')),
                ('order_instant_discount', models.IntegerField(default=0, verbose_name='주문 즉시할인')),
                ('total_instant_discount', models.IntegerField(default=0, verbose_name='전체 즉시할인')),
                ('order_brokerage_amount', models.IntegerField(default=0, verbose_name='주문정산금')),
                ('delivery_item_amount', models.IntegerField(default=0, verbose_name='배달비정산')),
                ('etc_item_amount', models.IntegerField(default=0, verbose_name='기타정산')),
                ('deduction_vat', models.IntegerField(default=0, verbose_name='공제VAT')),
            ],
            options={
                'verbose_name': '배민 주문 정보',
                'verbose_name_plural': '배민 주문 정보',
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('platform', models.CharField(choices=[('BAEMIN', '배달의민족'), ('COUPANG', '쿠팡이츠'), ('YOGIYO', '요기요')], db_index=True, max_length=10, verbose_name='플랫폼')),
                ('order_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='플랫폼 주문번호')),
                ('order_datetime', models.DateTimeField(verbose_name='주문일시')),
                ('status', models.CharField(max_length=20, verbose_name='주문상태')),
                ('delivery_type', models.CharField(max_length=20, verbose_name='배달유형')),
                ('pay_type', models.CharField(max_length=20, verbose_name='결제유형')),
                ('pay_amount', models.IntegerField(default=0, verbose_name='고객결제금액')),
                ('items_summary', models.CharField(blank=True, max_length=200, verbose_name='주문메뉴요약')),
                ('deposit_due_amount', models.IntegerField(default=0, verbose_name='최종정산금')),
                ('deposit_due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='정산예정일')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='원본 데이터')),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_order', to='sale.sale', verbose_name='POS 주문')),
            ],
            options={
                'verbose_name': '배달 주문',
                'verbose_name_plural': '배달 주문',
                'ordering': ['-order_datetime'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item_seq', models.PositiveSmallIntegerField(verbose_name='항목순번')),
                ('name', models.CharField(max_length=200, verbose_name='메뉴명')),
                ('quantity', models.IntegerField(default=1, verbose_name='수량')),
                ('total_price', models.IntegerField(default=0, verbose_name='금액')),
                ('discount_price', models.IntegerField(default=0, verbose_name='할인금액')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sale.deliveryorder', verbose_name='주문')),
            ],
            options={
                'verbose_name': '배달 주문 메뉴',
                'verbose_name_plural': '배달 주문 메뉴',
                'ordering': ['order', 'item_seq'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrderItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='옵션명')),
                ('price', models.IntegerField(default=0, verbose_name='옵션금액')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='sale.deliveryorderitem', verbose_name='메뉴')),
            ],
            options={
                'verbose_name': '배달 주문 옵션',
                'verbose_name_plural': '배달 주문 옵션',
                'ordering': ['item'],
            },
        ),
        migrations.CreateModel(
            name='DeliverySettlementDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.CharField(choices=[('ORDER', '주문'), ('DELIVERY', '배달'), ('ETC', '기타')], max_length=10, verbose_name='그룹')),
                ('code', models.CharField(max_length=50, verbose_name='항목코드')),
                ('name', models.CharField(max_length=100, verbose_name='항목명')),
                ('amount', models.IntegerField(default=0, verbose_name='금액')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_details', to='sale.deliveryorder', verbose_name='주문')),
            ],
            options={
                'verbose_name': '정산 상세',
                'verbose_name_plural': '정산 상세',
                'ordering': ['order', 'group'],
            },
        ),
        migrations.AddField(
            model_name='deliverybaemininfo',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baemin_info', to='sale.deliveryorder', verbose_name='배달 주문'),
        ),
        migrations.AddIndex(
            model_name='deliveryorder',
            index=models.Index(fields=['platform', 'order_datetime'], name='sale_delive_platfor_5d140e_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryorder',
            index=models.Index(fields=['platform', 'deposit_due_date'], name='sale_delive_platfor_5b8985_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deliveryorderitem',
            unique_together={('order', 'item_seq')},
        ),
    ]
