# Generated by Django 6.0.1 on 2026-04-04 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrderExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deposit_due_amount', models.IntegerField(default=0, verbose_name='입금예정금액')),
                ('deposit_due_date', models.DateField(blank=True, null=True, verbose_name='입금예정일')),
                ('pay_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='결제타입')),
                ('receive_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='수령방법')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_extra', to='sale.sale')),
            ],
            options={
                'verbose_name': '배달 주문 부가정보',
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('menu_name', models.CharField(max_length=200, verbose_name='배민 메뉴명')),
                ('quantity', models.IntegerField(default=1, verbose_name='수량')),
                ('price', models.IntegerField(default=0, verbose_name='단가')),
                ('discount_price', models.IntegerField(default=0, verbose_name='품목할인금액')),
                ('sale_item', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_item', to='sale.saleitem')),
            ],
            options={
                'verbose_name': '배달 주문 품목',
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrderItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('option_name', models.CharField(max_length=100, verbose_name='옵션명')),
                ('option_price', models.IntegerField(default=0, verbose_name='옵션금액')),
                ('option_discount_price', models.IntegerField(default=0, verbose_name='옵션할인금액')),
                ('delivery_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='sale.deliveryorderitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliverySettlementDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(max_length=50, verbose_name='정산분류')),
                ('item_name', models.CharField(max_length=100, verbose_name='항목명')),
                ('amount', models.IntegerField(verbose_name='금액')),
                ('api_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='항목코드')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='날짜')),
                ('baemin_commission_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='배민 중개수수료')),
                ('baemin_delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='배민 배달대행비')),
                ('baemin_ad_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='배민 광고비')),
                ('baemin_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='배민 VAT')),
                ('baemin_other_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='배민 기타수수료')),
                ('coupang_commission_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='쿠팡 중개수수료')),
                ('coupang_delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='쿠팡 배달대행비')),
                ('coupang_ad_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='쿠팡 광고비')),
                ('coupang_other_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='쿠팡 기타수수료')),
                ('yogiyo_commission_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='요기요 중개수수료')),
                ('yogiyo_delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='요기요 배달대행비')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_details', to='sale.sale')),
            ],
            options={
                'verbose_name': '일별 정산',
                'verbose_name_plural': '일별 정산',
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='DailySales',
        ),
    ]
