# Generated by Django 6.0.1 on 2026-04-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_deliveryorderextra_deliveryorderitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverysettlementdetail',
            name='date',
            field=models.DateField(db_index=True, verbose_name='날짜'),
        ),
    ]
